{"metadata":{"kernelspec":{"name":"python3","display_name":"Python 3 (ipykernel)","language":"python"},"language_info":{"name":"python","version":"3.12.8","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"markdown","source":"# Load Simple Workflow","metadata":{}},{"cell_type":"markdown","source":"## Aiida ","metadata":{}},{"cell_type":"code","source":"from python_workflow_definition.aiida import load_workflow_json\n\nfrom aiida import load_profile\nload_profile()","metadata":{"trusted":true},"outputs":[{"execution_count":1,"output_type":"execute_result","data":{"text/plain":"Profile<uuid='24c012c35e7c47e0a8221c4cd350ac57' name='pwd'>"},"metadata":{}}],"execution_count":1},{"cell_type":"code","source":"workgraph = load_workflow_json(file_name='workflow_simple.json')","metadata":{"trusted":true},"outputs":[],"execution_count":2},{"cell_type":"code","source":"# TODO: Create inputs rather than tasks out of data nodes\nworkgraph","metadata":{"trusted":true},"outputs":[{"execution_count":3,"output_type":"execute_result","data":{"text/plain":"NodeGraphWidget(settings={'minimap': True}, style={'width': '90%', 'height': '600px'}, value={'name': 'WorkGraâ€¦","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":1,"model_id":"f7e3c370d4dd46b1ac161756babc37c9"}},"metadata":{}}],"execution_count":3},{"cell_type":"code","source":"\nworkgraph.run()","metadata":{"trusted":true},"outputs":[{"name":"stderr","output_type":"stream","text":"03/24/2025 10:22:48 AM <293> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [3|WorkGraphEngine|continue_workgraph]: tasks ready to run: pickle_node3,pickle_node4\n03/24/2025 10:22:49 AM <293> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [3|WorkGraphEngine|on_wait]: Process status: Waiting for child processes: 11, 18\n03/24/2025 10:22:51 AM <293> aiida.scheduler.direct: [WARNING] Unrecognized job_state 'p' for job id Activating\n03/24/2025 10:22:51 AM <293> aiida.engine.transports: [ERROR] Exception whilst using transport:\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/transports.py\", line 106, in request_transport\n    yield transport_request.future\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n\nTask exception was never retrieved\nfuture: <Task finished name='Task-10' coro=<JobsList._ensure_updating.<locals>.updating() done, defined at /srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py:179> exception=IndexError('list index out of range')>\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/tasks.py\", line 314, in __step_run_and_handle_result\n    result = coro.send(None)\n             ^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 181, in updating\n    await self._update_job_info()\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n    self._jobs_cache = await self._get_jobs_from_scheduler()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n03/24/2025 10:22:51 AM <293> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 1 of do_update excepted, retrying after 20 seconds\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n    result = await coro()\n             ^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 195, in do_update\n    job_info = await cancellable.with_interrupt(update_request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n    result = await next(wait_iter)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/tasks.py\", line 631, in _wait_for_one\n    return f.result()  # May raise f.exception().\n           ^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/futures.py\", line 202, in result\n    raise self._exception.with_traceback(self._exception_tb)\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n    self._jobs_cache = await self._get_jobs_from_scheduler()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n03/24/2025 10:22:51 AM <293> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 1 of do_update excepted, retrying after 20 seconds\nTraceback (most recent call last):\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 205, in exponential_backoff_retry\n    result = await coro()\n             ^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/tasks.py\", line 195, in do_update\n    job_info = await cancellable.with_interrupt(update_request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/utils.py\", line 115, in with_interrupt\n    result = await next(wait_iter)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/tasks.py\", line 631, in _wait_for_one\n    return f.result()  # May raise f.exception().\n           ^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/asyncio/futures.py\", line 202, in result\n    raise self._exception.with_traceback(self._exception_tb)\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 132, in _update_job_info\n    self._jobs_cache = await self._get_jobs_from_scheduler()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/engine/processes/calcjobs/manager.py\", line 109, in _get_jobs_from_scheduler\n    scheduler_response = scheduler.get_jobs(**kwargs)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 269, in get_jobs\n    job_stats = super().get_jobs(jobs=jobs, user=user, as_dict=as_dict)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/scheduler.py\", line 361, in get_jobs\n    joblist = self._parse_joblist_output(retval, stdout, stderr)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/srv/conda/envs/notebook/lib/python3.12/site-packages/aiida/schedulers/plugins/direct.py\", line 253, in _parse_joblist_output\n    this_job.wallclock_time_seconds = self._convert_time(job[3])\n                                                         ~~~^^^\nIndexError: list index out of range\n"}],"execution_count":null},{"cell_type":"markdown","source":"## executorlib","metadata":{}},{"cell_type":"code","source":"from executorlib import SingleNodeExecutor","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"from python_workflow_definition.executorlib import load_workflow_json","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"with SingleNodeExecutor(max_workers=1) as exe:\n    result = load_workflow_json(file_name=\"workflow_simple.json\", exe=exe).result()","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"result","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"markdown","source":"## Jobflow","metadata":{}},{"cell_type":"code","source":"from jobflow.managers.local import run_locally","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"from python_workflow_definition.jobflow import load_workflow_json","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"flow = load_workflow_json(file_name=\"workflow_simple.json\")","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"result = run_locally(flow)\nresult","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"markdown","source":"## pyiron","metadata":{}},{"cell_type":"code","source":"from pyiron_base import Project","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"from python_workflow_definition.pyiron_base import load_workflow_json","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"pr = Project(\"test\")\npr.remove_jobs(recursive=True, silently=True)","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"delayed_object = load_workflow_json(project=pr, file_name=\"workflow_simple.json\")\ndelayed_object.draw()","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"delayed_object.pull()","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"pr.job_table()","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"markdown","source":"## Python","metadata":{}},{"cell_type":"code","source":"from python_workflow_definition.purepython import load_workflow_json","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"load_workflow_json(file_name=\"workflow_simple.json\")","metadata":{"trusted":true},"outputs":[],"execution_count":null}]}